### ISSUE TITLE
stream.write craps out after 140 writes

### ISSUE THREAD

**Issue by jmbldwn** [plotly/plotly-nodejs#14]
Getting this exception:

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: socket hang up
    at createHangUpError (http.js:1476:15)
    at Socket.socketOnEnd [as onend] (http.js:1572:23)
    at Socket.g (events.js:180:16)
    at Socket.emit (events.js:117:20)
    at _stream_readable.js:943:16
    at process._tickCallback (node.js:419:13)

Tried putting a try-catch block around stream.write but can't catch this.  Not sure how to debug.  Help?

**Comment by jmbldwn** [comment]
works beautifully up to that point, however...

**Comment by alexander-daniel** [comment]
Oh no! Sorry about that. Can you attach a gist with your client code?

**Comment by jmbldwn** [comment]
Here's my code: https://gist.github.com/jmbldwn/fafd9888b9a384bbef4b

I've narrowed it down a bit.  If I uncomment lines 25-27 to create the stream (and comment out line 28) it will crash after a while even if I don't send data.

**Comment by alexander-daniel** [comment]
@jmbldwn  Thanks!

Alright, so I'm not sure where the error is coming from your script. Are you able to get the simple example to stream more than 140 writes?

https://gist.github.com/alexander-daniel/919c58bacf53585b212d
(replace key and tokens with yours)

It's a bit hard for me to debug your case without the other modules that you've written, but I understand the repo might be private. If you want to share a bit more with me you can e-mail me @ alex.vados@gmail.com. I'll keep trying on my end to replicate as close as I can and see whats up.

**Comment by jmbldwn** [comment]
The problem with debugging this is it relies on a particular piece of equipment (a CS200 light/color meter) attached via USB (connected using node-usb), and another piece of equipment attached via a serial port (connected using node-serial).

Is there something I can do to my local module installation to spit out useful data that might enlighten us?

The thing that’s odd is that I only have to create the stream object.  Even if I don’t write to it, I get this crash.  No stream object, no crash.  Delightful.

On Jan 8, 2015, at 8:21 AM, Alejandro <notifications@github.com<mailto:notifications@github.com>> wrote:


@jmbldwn<https://github.com/jmbldwn> Thanks!

Alright, so I'm not sure where the error is coming from your script. Are you able to get the simple example to stream more than 140 writes?

https://gist.github.com/alexander-daniel/919c58bacf53585b212d
(replace key and tokens with yours)

It's a bit hard for me to debug your case without the other modules that you've written, but I understand the repo might be private. If you want to share a bit more with me you can e-mail me @ alex.vados@gmail.com<mailto:alex.vados@gmail.com>. I'll keep trying on my end to replicate as close as I can and see whats up.

**Comment by alexander-daniel** [comment]
I can't seem to replicate this without having the hardware..

**Comment by jmbldwn** [comment]
I went back to just plotting at the end of capture for the time being.

I’m back to streaming on some new tests I’m making and not running into trouble yet.  I could be a volume issue?  I was pushing lots of points before.

I do find the API for streaming a little cumbersome.  I have to provision the tokens on the service, so to avoid having to splatter them everywhere I am creating a node.js module to encapsulate things.

It would be nice if I could assign a string handle to a stream, so I can have different apps pushing points for a single plot without knowing the tokens.

-Jim

On Jan 16, 2015, at 11:45 AM, Alejandro <notifications@github.com<mailto:notifications@github.com>> wrote:


I can't seem to replicate this without having the hardware..

**Comment by jmbldwn** [comment]
It may also be that the http.stream returned by plotly.stream gets tired.  In my new code I’m only using it for one point at a time and no troubles so far.

On Jan 16, 2015, at 6:34 PM, Jim Baldwin <jim@baldw.in<mailto:jim@baldw.in>> wrote:

I went back to just plotting at the end of capture for the time being.

I’m back to streaming on some new tests I’m making and not running into trouble yet.  I could be a volume issue?  I was pushing lots of points before.

I do find the API for streaming a little cumbersome.  I have to provision the tokens on the service, so to avoid having to splatter them everywhere I am creating a node.js module to encapsulate things.

It would be nice if I could assign a string handle to a stream, so I can have different apps pushing points for a single plot without knowing the tokens.

-Jim

On Jan 16, 2015, at 11:45 AM, Alejandro <notifications@github.com<mailto:notifications@github.com>> wrote:


I can't seem to replicate this without having the hardware..

**Comment by alexander-daniel** [comment]
Glad to hear streaming is OK for you now. 

The volume of plotted points shouldn't matter, unless you're plotting > 200,000 or so. The streaming servers accept new points every 50ms, (if you send too quickly, we just throttle)

If you have any more issues, please open an issue, but I'm going to close this one, as I'm unable to recreate the original issue.
