### ISSUE TITLE
API for Removing Plots from my account

### ISSUE THREAD

**Issue by TheFive** [plotly/plotly-nodejs#18]
Due to a robots.txt failure on my homepage i have now 11.000 plots in my account.
It is not possible to remove them by the normal UI (did not find it). 

Is there an API for remove some / all plots ?

Christoph

**Comment by bpostlethwaite** [comment]
This feature will be arriving in v2 of our API, which should be ready in a few weeks. Check back to https://plot.ly/rest/ later this month.

**Comment by alexander-daniel** [comment]
@TheFive you can now use the method `deletePlot` to remove unwanted graphs!
