### ISSUE TITLE
Potly on Nodejs - “socket hang up and read ECONNRESET”

### ISSUE THREAD

**Issue by khoahoc00000** [plotly/plotly-nodejs#22]
I have some error when use Plotly on Nodejs, can you help me?

I write a demo to generate image from splotly api, every 20 seconds, server will create a chart image. Some images is good, but then throw err as image:

![screen shot 2015-04-20 at 3 37 18 pm](https://cloud.githubusercontent.com/assets/3798542/7244422/50308f26-e805-11e4-9dd6-e52822bd1281.png)
![screen shot 2015-04-21 at 8 45 13 am](https://cloud.githubusercontent.com/assets/3798542/7244424/56d7af94-e805-11e4-97ad-eeadaf0435f5.png)

My code:

setInterval(function() {
  plotly.getImage(figure, imgOpts, function(error, imageStream) {
    if (error) return console.log(error);
    var time = new Date();
    console.log("1--" + new Date());
    var fileStream = fs.createWriteStream(time + '.png');
    console.log("2--" + new Date());
    imageStream.pipe(fileStream);

    //            setTimeout(function(){
    //                console.log("3--"+new Date());
    //                //createPdfkit(time);
    //            },10000);

    //            imageStream.on('end',function(){
    //
    //            });
  });

}, 20000);

**Comment by alexander-daniel** [comment]
@khoahoc00000 I'm not sure I understand your problem. Some images generate, some do not?

Do you get back the proper bytes from the server? Do Any images fully generate OK?

**Comment by jimthomas47** [comment]
I have this same issue with node.js and plotly, 
I get good fully generated graphs for a while but it crashes within a few hours. 
 I've restarted it over and over for the past week or so.

Has anybody been able to make plotly run with node.js streaming mode indefinitely?  
Plotly seems great, but this instability is getting frustrating. It would be good to know that it can work.

(I'm logging the data and streamobject which gets sent every 30 sec for several hours before the crash.)
...
117.0 102.9 77.8
{"x":"2015-08-11 17:20:46.567","y":"117.0"}
{"x":"2015-08-11 17:20:46.567","y":"102.9"}
{"x":"2015-08-11 17:20:46.567","y":"77.8"}
116.8 103.0 77.7
{"x":"2015-08-11 17:21:19.322","y":"116.8"}
{"x":"2015-08-11 17:21:19.322","y":"103.0"}
{"x":"2015-08-11 17:21:19.322","y":"77.7"}
116.9 102.7 77.7
{"x":"2015-08-11 17:21:56.628","y":"116.9"}
{"x":"2015-08-11 17:21:56.628","y":"102.7"}
{"x":"2015-08-11 17:21:56.628","y":"77.7"}
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: read ECONNRESET
    at exports._errnoException (util.js:746:11)
    at TCP.onread (net.js:559:26)

**Comment by alexander-daniel** [comment]
@jimthomas47 with any continuous stream, sometimes the connection can/will be interrupted or disconnected. Can catch these errors in your script and make a new request and stream if it goes down? Would that be a solution for you?

**Comment by jimthomas47** [comment]
Thanks for the reply. Makes sense and your suggestion would work.
I am a mostly hardware guy / science teacher but I will try to figure out how to do it in the script.
(I wish the plotly folks would include this in their examples.)
