### ISSUE TITLE
Does not show Legend

### ISSUE THREAD

**Issue by Daomaster** [plotly/plotly-nodejs#25]
I'm layout variable, I set showLegend = true, but on the stream it does not show the legend. Does anyone know how to fix this, or the stream does not support legend?  

var layout = {
    filename: "stream-multiple-traces",
    fileopt: "overwrite",
    layout: {
      title: "streaming mock sensor data"
    },
    showlegend: true,
    world_readable: true
};

**Comment by etpinard** [comment]
Try
```js
var layout = {
  filename: "stream-multiple-traces",
  fileopt: "overwrite",
  layout: {
    title: "streaming mock sensor data",
    showlegend: true
  },
  world_readable: true
};
```

**Comment by Daomaster** [comment]
It works! Thanks @etpinard
