### ISSUE TITLE
Support for Non Ascii Character

### ISSUE THREAD

**Issue by lonelyeagle** [plotly/plotly-nodejs#26]
When put some Non Ascii Character (like Chinese Character) using UTF-8 enconding into title, the result return [Error: Missing required POST parameters: origin]. When remove such string, the result become OK. Does plotly support Non Ascii Character?

**Comment by alexander-daniel** [comment]
@lonelyeagle should be resolved here: https://github.com/plotly/plotly-nodejs/pull/32
Let me know if that works for you
