### ISSUE TITLE
does jpg format work

### ISSUE THREAD

**Issue by rschiavi** [plotly/plotly-nodejs#27]
i am able to generate png images, changing the format to jpg results in a server error response

{ [Error: Bad response status code 400] msg: undefined }

 var format = "jpg";
    var imgOpts = {
        format: format,
        width: 700,
        height: 500
    };

**Comment by chriddyp** [comment]
@alexander-daniel - I might be off here, but is it actually "jpeg", not "jpg"?

**Comment by alexander-daniel** [comment]
Yes, absolutely correct, it is `jpeg` and NOT `jpg`! Thanks!
