### ISSUE TITLE
Color change while streaming

### ISSUE THREAD

**Issue by Daomaster** [plotly/plotly-nodejs#28]
Just curious is it possible to change the color of a trace while it is streaming?

**Comment by theengineear** [comment]
Yes, there's nothing we do to prevent it. You just pass along the `color` attribute with a valid value.

Additionally, I'm pretty sure you can open the plot up in the GUI editor on Plotly and style it *while* it's streaming.

Have you run into an issue with it?

**Comment by Daomaster** [comment]
Got you gonna run some tests tomorrow then. Thanks a lot for the fast response.

**Comment by Daomaster** [comment]
So I did some test today, I was using the muti-trace example from the git, and I initialed the color. I can change the color using the GUI on the website, but can not achieve this by coding. Here is my code, in this one I was just simple put an if that if the value is -1 < and >1 then change the trace to black then else change it back.

https://gist.github.com/Daomaster/56a66b2c2239c844746e

**Comment by etpinard** [comment]
@Daomaster On line [53](https://gist.github.com/Daomaster/56a66b2c2239c844746e#file-plot-js-L53), this should be `first.line.color = "#000000"`

**Comment by Daomaster** [comment]
@etpinard  Hey I just tried it, still not changing it. 
Here is the outcome in plotly
https://plot.ly/~Daomaster/199/streaming-mock-sensor-data/

**Comment by etpinard** [comment]
Oh right, you gotta add that change to `signalstream` so that `signalstream.line.color === '#000000'`

**Comment by Daomaster** [comment]
Yeah I got the error the color is undefined 

Here:
https://gist.github.com/Daomaster/4845a14055f2500a7625

**Comment by etpinard** [comment]
you need to initialize the `signalstream.line` object (i.e. `signalstream = {}`) before filling it with `color: '#000000'`

**Comment by Daomaster** [comment]
got you

**Comment by Daomaster** [comment]
Okay I initialized it. var plotlystream = Plotly.stream(tokens[i], function() {}),
            signalstream = temp;
            signalstream.line = {};
        if (-1 < temp < 1) 
            {
                signalstream.line.color = "#000000";
            }
        else
            {
                signalstream.line.color = "#91C149";
            }

The error is gone, but still not changing color :(

**Comment by etpinard** [comment]
@Daomaster here's a full working example:

https://github.com/plotly/plotly-nodejs/blob/stream-style-attrs-ex/examples/streaming-style-attributes.js

I hope this helps

**Comment by Daomaster** [comment]
@etpinard  got it I think I didn't initialize the signalstream, cos Ionly got x: and y: from the random-signal but I don't have the line attributes inside the signalstream. Thanks a lot

**Comment by Daomaster** [comment]
I tried this one but it said on line 21 tokens.map "map" is undefined.

**Comment by etpinard** [comment]
have you filled in your [`config.json`](https://github.com/plotly/plotly-nodejs/blob/master/examples/config.json) ?

**Comment by Daomaster** [comment]
Yes I did, then I tried directly put them on the js file still got me the same error...

**Comment by etpinard** [comment]
is `tokens` an `Array` ?

**Comment by Daomaster** [comment]
no just one value

**Comment by etpinard** [comment]
Well, there you go. The [example](https://github.com/plotly/plotly-nodejs/blob/stream-style-attrs-ex/examples/streaming-style-attributes.js) I posted sends two streams; it iterates over `['streamToken1', 'streamToken2']`

**Comment by Daomaster** [comment]
Yes that fixed the problem, got it working thank! now I'm gonna try it with lines

**Comment by Daomaster** [comment]
still not working with lines, it works perfect with markers.

I basically change the mode to lines and change the marker into line, so it should be when y is below 1 the line change the color, I will do some more digging then.
 
https://gist.github.com/Daomaster/0cde02e99d64d0805072

**Comment by etpinard** [comment]
Oh right. That won't work for lines. My mistake.

In brief, plotly's streaming api appends a given plotly trace if data points are sent on each `stream.write` . As the line color is trace-wide attribute (unlike marker color which is handled point by point), our streaming endpoint can't update the whole trace (color) when the streaming data is received.

One solution is the send a data array instead of single points, e.g. have:
```js
var streamData = {
  x: [Math.random(), Math.random(), ...],
  y: [2 * Math.random(), 2, 2, ....],
  line: { color: '#91C149' }
};
```

In this case, the whole trace will be replotted with the streamed line color.

I hope this helps and I apologize for the confusion.
