### ISSUE TITLE
Error while trying to send multiple traces through multiple streams. 

### ISSUE THREAD

**Issue by chintanp** [plotly/plotly-nodejs#30]
Hi, 

Great Job plot.ly with a wonderfully intuitive, and simple API. Could use a forum for discussion though, in absence of which I am here to use the issues. 

I am trying to use streaming API for NodeJS, and it works perfectly for one sensor data, as explained in http://adilmoujahid.com/posts/2015/07/practical-introduction-iot-arduino-nodejs-plotly/ and my code here: https://github.com/chintanp/node_serial_uC/blob/master/stream_hum.js 

I need to send multiple sensor data though, and so I try further (commented to explain): https://gist.github.com/chintanp/5b79255d60c8fe03a8f0 

When I run it, I get the beautiful "All streams go!" message, but it errors in about a minute with 

    
    events.js:72
            throw er; // Unhandled 'error' event
                  ^
    Error: socket hang up
        at createHangUpError (http.js:1477:15)
        at Socket.socketOnEnd [as onend] (http.js:1573:23)
        at Socket.g (events.js:180:16)
        at Socket.emit (events.js:117:20)
        at _stream_readable.js:944:16
        at process._tickCallback (node.js:442:13)

    Process finished with exit code 8

So, I am guessing, the streams arent getting through and so the socket hangs after the preset time of 1 minute. Also, none my code in 

    sp.on('data' ....

gets executed, and all my breakpoints there stay without getting execution stop. 

What am I doing wrong ? I understand for two sub-plots, I will have to update the layout as in https://plot.ly/nodejs/subplots/ , but I am guessing thats not going to solve this or does it ?

**Comment by alexander-daniel** [comment]
@chintanp thanks for reaching out! This is probably the best place to report any issues re: the node API module.

It looks to me like your callback from the eventEmitter `sp` is not getting fired. 

I took your code and modified it to mock out the serial port stuff.

https://gist.github.com/alexander-daniel/3a12e3fddf5e7e1a50d5

Try that, it should work. I had to comment out your `isNaN` code for now, but you can get an idea how this should be working. Perhaps check on your serial connection to make sure that callback on `data` is getting fired properly.

Let me know if that helps!

**Comment by alexander-daniel** [comment]
@chintanp did this work for you?

**Comment by chintanp** [comment]
I have moved away from NodeJS for a while and cant test this to report, but will do it as soon as possible. 

This issue can be closed here.
