### ISSUE TITLE
Cannot catch some https error

### ISSUE THREAD

**Issue by twintaka** [plotly/plotly-nodejs#31]
Recently I'm having troubles unable to catch network errors which looks like node https is throwing.
e.g. getaddrinfo ENOTFOUND, read ECONNRESET

node https has on 'error' handling and I think adding following code will handle network error.

```
var req = https.request(options, handleResponse);
     req.write(payload);
     req.end();
+    req.on('error', function(e) {
+        onError(e)
+    });
```

**Comment by alexander-daniel** [comment]
@twintaka, May I see the code you're trying to run when you run into this? 

We catch http request errors for `plotly.plot` here: https://github.com/plotly/plotly-nodejs/blob/master/index.js#L96

Is this only happening on streaming plots?

**Comment by twintaka** [comment]
@alexander-daniel 
I should have write more details.
getImage and getFigure doesn't contains the error handling.
https://github.com/plotly/plotly-nodejs/blob/master/index.js#L221
https://github.com/plotly/plotly-nodejs/blob/master/index.js#L166
Thanks!

**Comment by twintaka** [comment]
I didn't try the streaming plots but the code looks like not handling the error.

**Comment by alexander-daniel** [comment]
Ah great, thank you! I will make a PR shortly to address these issues, thanks for pointing them out!

**Comment by twintaka** [comment]
Great! looking forward for the changes :+1:
