### ISSUE TITLE
How to use displayModeBar ?

### ISSUE THREAD

**Issue by ahetawal-p** [plotly/plotly-nodejs#42]
Is there a way to pass "displayModeBar" config option to Plotly.plot method for nodeJs.
Similar to what is present on the javascript exmaples like here : https://plot.ly/javascript/configuration-options/

**Comment by alexander-daniel** [comment]
@ahetawal-p this is just a wrapper around the plotly API endpoints, making it easier to make HTTP(s) requests to the servers to create and modify plots, but what you're asking is about `plotly.js`, the actual graphing library. Closing here as you probably want to ask the same question in the plotly.js repo! Thanks!
