### ISSUE TITLE
No data in image

### ISSUE THREAD

**Issue by trusk89** [plotly/plotly-nodejs#44]
So I'm trying to use it node, and upload the image cloudinary, but it just uploads an empty graph

This is how I'm using it

	var data = [
	  {
	    x: ["2013-10-04 22:23:00", "2013-11-04 22:23:00", "2013-12-04 22:23:00"],
	    y: [1, 3, 6],
	    type: "line"
	  }
	]

	var figure = { 'data': [data] };

	var imgOpts = {
    	format: 'png',
    	width: 800,
    	height: 600
	}

	plotly.getImage(figure, imgOpts, function (error, imageStream) {
    	if (error) return console.log (error)

	    var stream = cloudinary.uploader.upload_stream(function(result) { 
	    	sendImageMessage(globalSender, result["secure_url"], result["public_id"])
	    });
		var file_reader = imageStream.pipe(stream)
	});

And this is the upload

![13536149_1764201687126506_704657501_n](https://cloud.githubusercontent.com/assets/6096120/16383562/48b28f36-3c8e-11e6-9840-53acbedd2413.jpg)

**Comment by etpinard** [comment]
Thanks for checking plotly!

Looks like your feeding a 2D array of data to plotly i.e. line

```js
var figure = { 'data': [data] };

// should be
var figure = { 'data': data };
```

I hope this helps

**Comment by trusk89** [comment]
That was it, thank you!
