### ISSUE TITLE
Error Bad Response 500 for getImage()

### ISSUE THREAD

**Issue by shaedmorgan** [plotly/plotly-nodejs#68]
Any help would be great - or alternative options. 

I'm using getImage to create and store a plot in a google cloud bucket. I've been using this successfully for weeks now, and all of the sudden, with no changes to the code, I start getting this error. I've seen other issues with a 301 code, that make it seem like I need to to some switch to a new way to do this, but I don't know how. Any guidance, suggestions for quick fixes, etc. would be appreciated!

code:
![image](https://user-images.githubusercontent.com/71141995/102732810-acee5800-4309-11eb-97bd-535619afceaa.png)

error:
![image](https://user-images.githubusercontent.com/71141995/102732673-584add00-4309-11eb-8c84-d3112604a94f.png)

**Comment by shaedmorgan** [comment]
I've narrowed it down to the fact that I display some text that is not a UTF-8 character, but it's not reading it correctly. It's the upward pointing white triangle "\u25B3" - when I put that in the code, it  still gives me the error

(see issue #43 for reference!)

**Comment by edencheung** [comment]
Same problem here, plotly gives me a 500 error when I try to render a graph containing a character like "ç". However, the weird thing is that when I do ploty.plot() and click into the URL, it works perfectly fine.

**Comment by shaedmorgan** [comment]
Following the instructions listed in this pull request and a bit more tinkering fixed the issue for me. You basically just need to change the instructions on how the JSON gets read to include all utf-8 special characters:

Hope this helps! Worked for me.

https://github.com/plotly/plotly-nodejs/pull/49

**Comment by shaedmorgan** [comment]
Following the instructions listed in this pull request and a bit more tinkering fixed the issue for me. You basically just need to change the instructions on how the JSON gets read to include all utf-8 special characters:

Hope this helps! Worked for me.

#49

**Comment by shaedmorgan** [comment]
> Same problem here, plotly gives me a 500 error when I try to render a graph containing a character like "ç". However, the weird thing is that when I do ploty.plot() and click into the URL, it works perfectly fine.

I hope my solution above works for you!
